name: XML & YAML Validations
on: push
jobs:
  xml-validation:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout
          uses: actions/checkout@master  
        - name: XML
          uses: anyone-developer/anyone-validate-xml@main
          with:
            file-extension: '.config,.xml'
            ignore-files: 'README.md'
            ignore-directories: '.git'
            read-path: .
  yaml-validation:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout-2
        uses: actions/checkout@v3
      - name: Check file existence
        id: CheckFile
        continue-on-error: true
        uses: andstor/file-existence-action@v2
        with:
          files: "values.yml"
          fail: true
      - name: yaml-lint
        if: steps.CheckFile.outcome == 'success'
        uses: ibiqlik/action-yamllint@v3
        with:
          file_or_dir: values.yml
          
